permissions:
  contents: write

name: Android CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Decode signing key
      run: |
        echo "${{ secrets.SIGNING_KEY }}" | base64 -d > release-keystore.jks

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Install Android Build Tools
      run: sudo apt-get install -y android-sdk-build-tools

    - name: Build release APK
      run: ./gradlew assembleRelease

    - name: Align APK
      run: |
        $ANDROID_HOME/build-tools/34.0.0/zipalign -v 4 \
          app/build/outputs/apk/release/app-release-unsigned.apk \
          app/build/outputs/apk/release/app-release-aligned.apk

    - name: Sign APK
      run: |
        apksigner sign \
          --ks release-keystore.jks \
          --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} \
          --key-pass pass:${{ secrets.KEY_PASSWORD }} \
          --ks-key-alias ${{ secrets.KEY_ALIAS }} \
          --v1-signing-enabled true \
          --v2-signing-enabled true \
          app/build/outputs/apk/release/app-release-aligned.apk

    - name: Verify signature
      run: jarsigner -verify -verbose -certs app/build/outputs/apk/release/app-release-aligned.apk

    - name: Export version tag
      run: echo "VERSION_TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV

    - name: Rename final APK
      run: |
        mv app/build/outputs/apk/release/app-release-aligned.apk \
           BoutScoring-v${VERSION_TAG}.apk

    - name: Upload final APK
      uses: actions/upload-artifact@v4
      with:
        name: BoutScoring
        path: BoutScoring-v${{ env.VERSION_TAG }}.apk
